# Generated by Django 5.2.1 on 2026-04-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery_payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('PAID', 'Paid')], default='PENDING', help_text='Legacy field, synced with customer_payment_status', max_length=20),
        ),
    ]
