# Generated by Django 5.2.1 on 2026-04-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer_payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
