# Generated by Django 5.2.1 on 2026-04-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('DELIVERY_PARTNER', 'Delivery Partner'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
