# Generated by Django 5.2.1 on 2026-04-23 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_state_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceableCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_service_available', models.BooleanField(default=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_availability', to='users.city')),
            ],
        ),
    ]
