# Generated by Django 5.2.1 on 2026-05-14 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_serviceablecity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='users.city')),
            ],
            options={
                'verbose_name_plural': 'City Pincodes',
                'unique_together': {('city', 'pincode')},
            },
        ),
    ]
