# Generated by Django 5.2.1 on 2026-04-20 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_wallettransaction_status_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='aadhaar_card_copy',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/aadhaar/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Aadhaar format (12 digits required)', regex='^[0-9]{12}$')]),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='authorized_letter',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/auth/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_passbook_copy',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/bank/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='owner_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/owners/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_card_copy',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/pan/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Invalid PAN format', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')]),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/shops/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_license_copy',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/license/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid GST format', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
    ]
