# Generated by Django 5.2.1 on 2026-04-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_sellerprofile_aadhaar_card_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellerwallet',
            name='payable_to_admin',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission owed to admin for COD orders', max_digits=12),
        ),
        migrations.AddField(
            model_name='sellerwallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellerwallet',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer (Online)'), ('UPI', 'UPI (Online)'), ('CASH', 'Cash (Offline)'), ('MANUAL_TRANSFER', 'Manual Transfer (Offline)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='category',
            field=models.CharField(choices=[('SALE', 'Sale (Online)'), ('COMMISSION', 'Commission Due (COD)'), ('WITHDRAWAL', 'Withdrawal'), ('SETTLEMENT', 'Admin Settlement')], default='SALE', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer (Online)'), ('UPI', 'UPI (Online)'), ('CASH', 'Cash (Offline)'), ('MANUAL_TRANSFER', 'Manual Transfer (Offline)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Reference for online transfer or receipt number for cash', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=15),
        ),
    ]
