# Generated by Django 5.2.1 on 2026-04-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_sellerwallet_available_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerwallet',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='sellerwallet',
            name='payable_to_admin',
        ),
        migrations.RemoveField(
            model_name='sellerwallet',
            name='pending_balance',
        ),
        migrations.RemoveField(
            model_name='sellerwallet',
            name='total_withdrawn',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
    ]
