# Generated by Django 5.2.1 on 2026-04-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_remove_sellerwallet_available_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellerwallet',
            name='payable_to_admin',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='COD commissions due to platform', max_digits=12),
        ),
        migrations.AddField(
            model_name='sellerwallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellerwallet',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='category',
            field=models.CharField(choices=[('SALE', 'Sale'), ('COMMISSION', 'Commission Deduction'), ('WITHDRAWAL', 'Withdrawal'), ('SETTLEMENT', 'Settlement')], default='SALE', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
    ]
