# Generated by Django 5.2.1 on 2026-04-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_sellerwallet_available_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Percentage commission, e.g., 7.00 for 7%', max_digits=5),
        ),
    ]
