# Generated by Django 5.2.1 on 2026-04-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_alter_sellerprofile_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='offered_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission offered by seller during registration', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Final percentage commission set by admin', max_digits=5),
        ),
    ]
