# Generated by Django 5.2.1 on 2026-04-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0011_sellerprofile_offered_commission_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='offered_commission_rate',
        ),
    ]
