# Generated by Django 5.2.1 on 2026-04-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0012_remove_sellerprofile_offered_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage commission, e.g., 5.00 for 5%', max_digits=5),
        ),
    ]
