# Generated by Django 5.2.1 on 2026-05-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0013_alter_sellerprofile_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_account_type',
            field=models.CharField(blank=True, help_text='Savings / Current / etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Direct commission amount per sale', max_digits=10),
        ),
    ]
