# Generated by Django 5.2.1 on 2026-05-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0014_sellerprofile_bank_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='has_been_approved',
            field=models.BooleanField(default=False),
        ),
    ]
