# Generated by Django 5.2.1 on 2026-09-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0015_sellerprofile_has_been_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='msme_letter_copy',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/msme/'),
        ),
    ]
