# Generated by Django 5.2.1 on 2026-09-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0016_sellerprofile_msme_letter_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
