# Generated by Django 5.2.1 on 2026-04-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('support_hours', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Contact Settings',
            },
        ),
    ]
