# Generated by Django 5.2.1 on 2026-04-08 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_person_order_is_refunded_and_more'),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to='orders.order'),
        ),
    ]
