# Generated by Django 5.2.1 on 2026-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_delivery_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='exchange_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_exchange',
            field=models.BooleanField(default=False),
        ),
    ]
