# Generated by Django 5.2.1 on 2026-05-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_admin_commission_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Order Assigned'), ('INSTALLATION_SCHEDULED', 'Installation Scheduled'), ('INSTALLATION_IN_PROGRESS', 'Installation In Progress'), ('WORK_ONGOING', 'Work Ongoing'), ('WORK_CONTINUED_TOMORROW', 'Work Continued Tomorrow'), ('INSTALLATION_COMPLETED', 'Installation Completed'), ('CUSTOMER_CONFIRMATION_PENDING', 'Customer Confirmation Pending'), ('INSTALLATION_VERIFIED', 'Installation Verified'), ('CLOSED_SUCCESSFULLY', 'Closed Successfully'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUNDED', 'Refunded'), ('COMPLETED', 'Completed')], default='PENDING', max_length=35),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Order Assigned'), ('INSTALLATION_SCHEDULED', 'Installation Scheduled'), ('INSTALLATION_IN_PROGRESS', 'Installation In Progress'), ('WORK_ONGOING', 'Work Ongoing'), ('WORK_CONTINUED_TOMORROW', 'Work Continued Tomorrow'), ('INSTALLATION_COMPLETED', 'Installation Completed'), ('CUSTOMER_CONFIRMATION_PENDING', 'Customer Confirmation Pending'), ('INSTALLATION_VERIFIED', 'Installation Verified'), ('CLOSED_SUCCESSFULLY', 'Closed Successfully'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUNDED', 'Refunded'), ('COMPLETED', 'Completed')], max_length=35),
        ),
    ]
