# Generated by Django 5.2.1 on 2026-05-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status_alter_ordertracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Order Assigned'), ('SCHEDULED', 'Installation Scheduled'), ('INSTALLATION_STARTED', 'Installation Started'), ('IN_PROGRESS', 'Work In Progress'), ('CONTINUED_TOMORROW', 'Work Continued Tomorrow'), ('RESUMED', 'Installation Resumed'), ('COMPLETED', 'Installation Completed'), ('AWAITING_CONFIRMATION', 'Awaiting Customer Confirmation'), ('VERIFIED', 'Installation Verified'), ('CLOSED', 'Closed Successfully'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Order Assigned'), ('SCHEDULED', 'Installation Scheduled'), ('INSTALLATION_STARTED', 'Installation Started'), ('IN_PROGRESS', 'Work In Progress'), ('CONTINUED_TOMORROW', 'Work Continued Tomorrow'), ('RESUMED', 'Installation Resumed'), ('COMPLETED', 'Installation Completed'), ('AWAITING_CONFIRMATION', 'Awaiting Customer Confirmation'), ('VERIFIED', 'Installation Verified'), ('CLOSED', 'Closed Successfully'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUNDED', 'Refunded')], max_length=30),
        ),
    ]
