# Generated by Django 5.2.1 on 2026-05-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status_alter_ordertracking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('max_bookings', models.PositiveIntegerField(default=5)),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('pincode', 'date', 'time_slot')},
            },
        ),
    ]
