# Generated by Django 5.2.1 on 2026-05-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_deliveryslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryslot',
            name='max_bookings',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
