# Generated by Django 5.2.1 on 2026-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
