# Generated by Django 5.2.1 on 2026-04-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_comboproduct'),
        ('users', '0006_state_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='users.city'),
        ),
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.make'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='users.state'),
        ),
    ]
