# Generated by Django 5.2.1 on 2026-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_city_product_make_product_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exchange_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='exchange_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
