# Generated by Django 5.2.1 on 2026-04-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_exchange_available_product_exchange_discount'),
        ('sellers', '0009_sellerwallet_available_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='sellers.sellerprofile'),
        ),
    ]
