# Generated by Django 5.2.1 on 2026-04-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_comboproduct_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comboproduct',
            name='seller',
        ),
    ]
