# Generated by Django 5.2.1 on 2026-04-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_searchquery'),
        ('users', '0007_serviceablecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to='users.city'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='compatible_vehicles',
            field=models.ManyToManyField(blank=True, related_name='compatible_combos', to='products.vehicle'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to='products.make'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to='products.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to='users.state'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='warranty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ComboProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='combos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('combo_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.comboproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ComboProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('combo_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.comboproduct')),
            ],
        ),
    ]
