# Generated by Django 5.2.1 on 2026-05-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_comboproduct_city_comboproduct_compatible_vehicles_and_more'),
        ('users', '0007_serviceablecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='combos', to='products.brand'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='combos', to='products.category'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='exchange_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='exchange_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='comboproduct',
            name='city',
        ),
        migrations.RemoveField(
            model_name='comboproduct',
            name='make',
        ),
        migrations.RemoveField(
            model_name='comboproduct',
            name='model',
        ),
        migrations.RemoveField(
            model_name='comboproduct',
            name='state',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='make',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='combos', to='users.city'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='make',
            field=models.ManyToManyField(blank=True, related_name='combos', to='products.make'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='model',
            field=models.ManyToManyField(blank=True, related_name='combos', to='products.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='state',
            field=models.ManyToManyField(blank=True, related_name='combos', to='users.state'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='products', to='users.city'),
        ),
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.make'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.ManyToManyField(blank=True, related_name='products', to='users.state'),
        ),
    ]
