# Generated by Django 5.2.1 on 2026-05-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_comboproduct_brand_comboproduct_category_and_more'),
        ('users', '0008_citypincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='pincodes',
            field=models.ManyToManyField(blank=True, related_name='combos', to='users.citypincode'),
        ),
        migrations.AddField(
            model_name='product',
            name='pincodes',
            field=models.ManyToManyField(blank=True, related_name='products', to='users.citypincode'),
        ),
    ]
