# Generated by Django 5.2.1 on 2026-05-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_shared_sequence_ids'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE SEQUENCE IF NOT EXISTS products_shared_id_seq START WITH 2000;
                
                -- Handle Product table
                ALTER TABLE products_product ALTER COLUMN id DROP IDENTITY IF EXISTS;
                ALTER TABLE products_product ALTER COLUMN id SET DEFAULT nextval('products_shared_id_seq');
                
                -- Handle ComboProduct table
                ALTER TABLE products_comboproduct ALTER COLUMN id DROP IDENTITY IF EXISTS;
                ALTER TABLE products_comboproduct ALTER COLUMN id SET DEFAULT nextval('products_shared_id_seq');
            """,
            reverse_sql="""
                ALTER TABLE products_product ALTER COLUMN id DROP DEFAULT;
                ALTER TABLE products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
                
                ALTER TABLE products_comboproduct ALTER COLUMN id DROP DEFAULT;
                ALTER TABLE products_comboproduct ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
                
                DROP SEQUENCE IF EXISTS products_shared_id_seq;
            """
        ),
    ]
