# Generated by Django 5.2.12 on 2026-05-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_shared_id_sequence_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
