# Generated by Django 5.2.1 on 2026-09-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productreview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric'), ('Any', 'Any')], default='Any', max_length=50),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=28.0, help_text='GST Percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric'), ('Any', 'Any')], default='Any', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=28.0, help_text='GST Percentage (e.g., 28.00)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='comboproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base Price (Exclusive of GST)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base Price (Exclusive of GST)', max_digits=10),
        ),
    ]
